# Generated by Django 3.2.5 on 2021-08-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210814_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtime',
            name='feed_time1',
            field=models.IntegerField(null=True),
        ),
    ]
