# Generated by Django 3.2.5 on 2021-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='func',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='func',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
