# Generated by Django 3.2.5 on 2021-08-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210812_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='func',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
